{
  package pigeon

  import (
    "errors"
  )
}

Grammar <- ID OptionalID2 { return nil, errors.New("B") }

// Removing the "?" fixes the bug.
OptionalID <- ID?  { return nil, errors.New("E") }

OptionalID2 <- OptionalID { return nil, errors.New("C") }

// Removing this unused rule definition fixes the bug!
OptionalID3 <- OptionalID

ID <- "A" !{ return true, nil } { return nil, errors.New("D") }

